name: Reusable Deploy Workflow

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      docker_compose_file:
        required: true
        type: string
    secrets:
      POSTGRES_USER:
        required: true
      POSTGRES_PASSWORD:
        required: true
      POSTGRES_DB:
        required: true
      DATABASE_URL:
        required: true

jobs:
  deploy:
    runs-on: [self-hosted, "${{ inputs.environment }}"]
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Environment File
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

      - name: Run Docker Compose WITH BUILD CACHE
        run: |
          docker-compose -f ${{ inputs.docker_compose_file }} down --remove-orphans
          docker-compose -f ${{ inputs.docker_compose_file }} pull
          DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 \
          docker-compose -f ${{ inputs.docker_compose_file }} build --progress=plain
          docker-compose -f ${{ inputs.docker_compose_file }} up -d
