name: Deploy to Dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to Dev environment'
        required: true
        default: 'yes'

jobs:
  deploy-dev:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: dev
      docker_compose_file: docker-compose.dev.yml
    secrets: inherit
