name: Deploy to Prod

on:
  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to Prod environment'
        required: true
        default: 'yes'

jobs:
  deploy-prod:
    runs-on: [self-hosted, prod]
    environment: prod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Environment File
        run: |
          echo "POSTGRES_USER=${{ secrets.DB_USERNAME }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.DB_NAME }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

      - name: Run Docker Compose for Prod
        run: |
          docker-compose down --remove-orphans
          docker-compose pull
          docker-compose up -d --build
