name: Deploy to Prod

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to Prod environment'
        required: true
        default: 'yes'

jobs:
  deploy-prod:
    runs-on: [self-hosted, prod]
    environment: prod
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Environment File
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env

      - name: Run Docker Compose for Prod
        run: |
          docker-compose -f docker-compose.prod.yml down --remove-orphans
          docker-compose -f docker-compose.prod.yml pull
          docker-compose -f docker-compose.prod.yml up -d --build
