name: Deploy to Prod

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to Prod environment'
        required: true
        default: 'yes'

jobs:
  deploy-prod:
    uses: ./.github/workflows/deploy.yml
    with:
      environment: prod
      docker_compose_file: docker-compose.prod.yml
    secrets: inherit
